chat:
  - name: gpt-3.5-turbo
    model_format: openvino
    path: C:\\Users\\EDY\\Desktop\\chatglm3.openvino\\chatglm3-6b-int4
    device:
      - GPU
    port: 8011

embed:
  - name: text-embedding-ada-002
    path: D:\\model\\bge-large-zh-v1.5
    device:
      - 0
    batchsize: 64
    port: 8013

service:
  host: 127.0.0.1
  port: 8010
